### PR TITLE
Render API commands as commandline references

### PR DESCRIPTION
**Pull request by adswa**
This is how this change makes the docs look:

image

image

image

### CODE REVIEW

**Comment by adswa** [comment]
The Appveyor MacOS build seems to be the unsupported Mac 10.5 Catalina version that home brew refuses to work with.

**Comment by adswa** [comment]
The Appveyor MacOS build seems to be the unsupported Mac 10.5 Catalina version that home brew refuses to work with.

**Comment by adswa** [comment]
The appveyor failures would be fixed by #337.

**Comment by adswa** [comment]
green now

**Review by christian-monch — APPROVED** [review]
Great, thanks a lot @adswa

**Pull request merged**
